# Generated by Django 4.0.3 on 2023-06-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_author_description_alter_author_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.IntegerField(default=0),
        ),
    ]
