# Generated by Django 4.0.3 on 2023-06-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='image/person/08.jpg', upload_to='image/person/'),
        ),
    ]
